# Generated by Django 5.0.7 on 2024-07-29 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_client_convert_to_lead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="convert_to_lead",
        ),
    ]
