# Generated by Django 5.0.7 on 2024-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_remove_client_convert_to_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="convert_to_client",
            field=models.BooleanField(default=True),
        ),
    ]
