# Generated by Django 5.0.7 on 2024-08-01 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_client_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("first_name",)},
        ),
    ]
