# Generated by Django 5.0.7 on 2024-08-01 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0002_lead_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("first_name",)},
        ),
    ]
