# Generated by Django 5.0.7 on 2024-08-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0004_leadcomment_delete_leadnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadcomment",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="lead.lead",
            ),
        ),
    ]
