# Generated by Django 5.0.7 on 2024-08-07 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0005_alter_leadcomment_lead"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leadcomment",
            old_name="Comment",
            new_name="comment",
        ),
    ]
